### ISSUE TITLE
Add audit logging to lab 7 - secure by design

### ISSUE THREAD

**Issue by altenstedt** [Omegapoint/defence-in-depth#7]
We really want to show a pattern for audit logging in the secure by design lab. It is a very important aspect that you need to consider, and a pattern that we know works would benefit readers.

For example:

```cs
await auditService.Log(DomainEvent.ProductRead, product);
```

One thing to consider is how to deal with the domain object. It can contain secret information that should be removed first. We can do it by mapping to a separate contract class, or by anonymising the domain object.  You need to choose when you implement this issue.

**Comment by TobiasAhnoff** [comment]
This has been implemented in #13
